import {
  FaCode,
  FaMobile,
  FaPaintBrush,
  FaBullhorn,
  FaHandshake,
  FaCloud,
  FaCalculator,
  FaUsers,
  FaLaptopCode,
  FaSearch,
  FaShareAlt,
  FaGoogle,
  FaEnvelope,
  FaUserTie,
  FaChartLine,
  FaShieldAlt,
  FaServer,
  FaFileInvoiceDollar,
  FaClipboardList,
  FaDesktop,
  FaCog,
  FaDatabase,
  FaTools,
} from "react-icons/fa";

import {
  FaReact,
  FaNodeJs,
  FaFileAlt,
  FaCogs,
  FaLink,
  FaPython,
  FaPhp,
  FaHtml5,
  FaCss3Alt,
  FaJs,
  FaAngular,
  FaLaravel,
  FaWordpress,
  FaShopify,
  FaAws,
  FaMapMarkerAlt,
  FaBug,
  FaGoogle as FaGoogleCloud,
} from "react-icons/fa";
import seo from "../../../assets/seo.png";

// const serviceLocations = [
//   "Badarpur",
//   "Faridabad",
//   "Greater Faridabad",
//   "Ballabgarh",
//   "Palwal",
//   "Sohna",
//   "Surajkund",
//   "Tigaon",
//   "NIT Faridabad",
//   "Sector 15 Faridabad",
//   "Old Faridabad",
//   "New Industrial Town",
//   "Delhi NCR",
//   "Gurgaon",
//   "Noida",
//   "Greater Noida",
//   "South Delhi",
//   "East Delhi",
//   "Nehru Place",
//   "Jasola",
//   "Vrindavan",
//   "Mathura",
// ];


const serviceLocations = [
  // ───── FARIDABAD SECTORS ─────
  "Sector 1 Faridabad",
  "Sector 2 Faridabad",
  "Sector 3 Faridabad",
  "Sector 4 Faridabad",
  "Sector 5 Faridabad",
  "Sector 6 Faridabad",
  "Sector 7 Faridabad",
  "Sector 8 Faridabad",
  "Sector 9 Faridabad",
  "Sector 10 Faridabad",
  "Sector 11 Faridabad",
  "Sector 12 Faridabad",
  "Sector 14 Faridabad",
  "Sector 15 Faridabad",
  "Sector 16 Faridabad",
  "Sector 17 Faridabad",
  "Sector 19 Faridabad",
  "Sector 20 Faridabad",
  "Sector 21 Faridabad",
  "Sector 21A Faridabad",
  "Sector 21B Faridabad",
  "Sector 21C Faridabad",
  "Sector 21D Faridabad",
  "Sector 22 Faridabad",
  "Sector 23 Faridabad",
  "Sector 24 Faridabad",
  "Sector 25 Faridabad",
  "Sector 26 Faridabad",
  "Sector 27 Faridabad",
  "Sector 27A Faridabad",
  "Sector 27B Faridabad",
  "Sector 28 Faridabad",
  "Sector 29 Faridabad",
  "Sector 30 Faridabad",
  "Sector 31 Faridabad",
  "Sector 32 Faridabad",
  "Sector 33 Faridabad",
  "Sector 34 Faridabad",
  "Sector 35 Faridabad",
  "Sector 36 Faridabad",
  "Sector 37 Faridabad",
  "Sector 38 Faridabad",
  "Sector 39 Faridabad",
  "Sector 40 Faridabad",
  "Sector 41 Faridabad",
  "Sector 42 Faridabad",
  "Sector 43 Faridabad",
  "Sector 44 Faridabad",
  "Sector 45 Faridabad",
  "Sector 46 Faridabad",
  "Sector 47 Faridabad",
  "Sector 48 Faridabad",
  "Sector 49 Faridabad",
  "Sector 50 Faridabad",
  "Sector 55 Faridabad",
  "Sector 56 Faridabad",
  "Sector 57 Faridabad",
  "Sector 58 Faridabad",
  "Sector 59 Faridabad",
  "Sector 62 Faridabad",
  "Sector 63 Faridabad",
  "Sector 65 Faridabad",
  "Sector 66 Faridabad",
  "Sector 75 Faridabad",
  "Sector 76 Faridabad",
  "Sector 77 Faridabad",
  "Sector 78 Faridabad",
  "Sector 79 Faridabad",
  "Sector 80 Faridabad",
  "Sector 81 Faridabad",
  "Sector 82 Faridabad",
  "Sector 83 Faridabad",
  "Sector 84 Faridabad",
  "Sector 85 Faridabad",
  "Sector 86 Faridabad",
  "Sector 87 Faridabad",
  "Sector 88 Faridabad",
  "Sector 89 Faridabad",

  // ───── FARIDABAD MAIN AREAS ─────
  "NIT Faridabad",
  "Old Faridabad",
  "New Industrial Town",
  "New Industrial Town (NIT)",
  "Ballabgarh",
  "Badarpur",
  "Surajkund",
  "Tigaon",
  "Mujesar",
  "Bata Chowk",
  "HUDA Faridabad",
  "BPTP Faridabad",
  "Greenfield Colony Faridabad",
  "Sunbeam Colony Faridabad",
  "Crown Interiorz Mall Area",
  "Omaxe World Street Faridabad",
  "Pari Chowk Faridabad",
  "Sainik Colony Faridabad",
  "Sanjay Colony Faridabad",
  "Shastri Colony Faridabad",
  "Nehru Colony Faridabad",
  "Gandhi Colony Faridabad",
  "Vidya Colony Faridabad",
  "DLF Colony Faridabad",
  "Anangpur Faridabad",
  "Mohna Road Faridabad",
  "Agra Canal Road Faridabad",
  "Mathura Road Faridabad",
  "Delhi Mathura Road Faridabad",
  "Pali Faridabad",
  "Dhauj Faridabad",
  "Badkhal Faridabad",
  "Badkhal Lake Area",
  "Dabua Colony Faridabad",
  "Subhash Colony Faridabad",
  "Surya Vihar Faridabad",
  "Arya Nagar Faridabad",
  "Shiv Durga Vihar",
  "Lakhi Pur Faridabad",
  "Faridabad Railway Station Area",
  "Escorts Faridabad",
  "NTPC Colony Faridabad",
  "Harijanwas Faridabad",
  "Chhainsa Faridabad",
  "Bhaini Faridabad",

  // ───── GREATER FARIDABAD / NEARBY ─────
  "Greater Faridabad",
  "Faridabad Extension",
  "Palwal",
  "Sohna",
  "Hodal",
  "Hathin",
  "Prithla",
  "Aurangabad Haryana",
  "Nuh",
  "Rewari",
  "Bhiwani",

  // ───── DELHI NCR ─────
  "Delhi NCR",
  "South Delhi",
  "East Delhi",
  "North Delhi",
  "West Delhi",
  "Central Delhi",
  "Nehru Place",
  "Jasola",
  "Sarita Vihar",
  "Okhla",
  "Lajpat Nagar",
  "Greater Kailash",
  "Malviya Nagar",
  "Kalkaji",
  "Govindpuri",
  "Tughlakabad",
  "Badarpur Delhi",
  "Molar Band",
  "Sangam Vihar",
  "Palam Vihar",
  "Uttam Nagar",
  "Dwarka",
  "Rohini",
  "Pitampura",
  "Janakpuri",
  "Rajouri Garden",
  "Punjabi Bagh",
  "Paschim Vihar",
  "Shalimar Bagh",
  "Model Town Delhi",
  "Saket",
  "Vasant Kunj",
  "Hauz Khas",
  "Karol Bagh",
  "Connaught Place",
  "Shahdara",
  "Preet Vihar",
  "Laxmi Nagar",
  "Krishna Nagar",
  "Mayur Vihar",
  "Patparganj",
  "Geeta Colony",

  // ───── GURGAON / GURUGRAM ─────
  "Gurgaon",
  "Gurugram",
  "DLF Gurgaon",
  "Cyber City Gurgaon",
  "Sohna Road Gurgaon",
  "Golf Course Road Gurgaon",
  "MG Road Gurgaon",
  "Old Gurgaon",
  "Palam Vihar Gurgaon",
  "Sector 14 Gurgaon",
  "Sector 29 Gurgaon",
  "Sector 56 Gurgaon",
  "Manesar",

  // ───── NOIDA / GREATER NOIDA ─────
  "Noida",
  "Greater Noida",
  "Noida Extension",
  "Sector 18 Noida",
  "Sector 62 Noida",
  "Sector 63 Noida",
  "Sector 125 Noida",
  "Sector 132 Noida",
  "Sector 137 Noida",
  "Sector 150 Noida",
  "Knowledge Park Greater Noida",
  "Omega Greater Noida",
  "Alpha Greater Noida",

  // ───── MATHURA / VRINDAVAN ─────
  "Mathura",
  "Vrindavan",
  "Govardhan",
  "Barsana",
];
export const servicesData = [
  {
    id: 1,
    title: "Website Development",
    slug: "website-development-company",
    tagline: "We Don't Just Build Websites — We Build Brands Online",
    description:
      "Beautiful, fast, and SEO-ready websites that convert visitors into loyal customers.",
    detailedDescription:
      "Your website is more than a digital address — it's your brand's voice, your customer's first impression, and your most powerful sales tool. We design and develop websites that are visually stunning, lightning-fast, secure, and built to convert visitors into customers. Whether you're a startup, a growing SME, or a large enterprise, we ensure your online presence works as hard as you do.",
    icon: FaCode,
    image:
      "https://plus.unsplash.com/premium_photo-1678565869434-c81195861939?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8d2ViJTIwZGV2ZWxvcGVyfGVufDB8fDB8fHww",
    category: "Development",
    locations: serviceLocations,
    offerings: [
      {
        title: "Custom Web Design",
        description: "Unique, brand-aligned, and conversion-focused layouts.",
        icon: FaPaintBrush,
      },
      {
        title: "Responsive & Mobile-First Development",
        description: "Perfect on every screen size.",
        icon: FaMobile,
      },
      {
        title: "E-Commerce Solutions",
        description: "High-performing online stores with secure checkout.",
        icon: FaShieldAlt,
      },
      {
        title: "CMS Development",
        description: "WordPress, Shopify, Magento, or custom-built platforms.",
        icon: FaWordpress,
      },
      {
        title: "Web Applications",
        description: "Scalable solutions for complex business needs.",
        icon: FaLaptopCode,
      },
      {
        title: "SEO-Optimized Code",
        description: "Built to rank higher on search engines.",
        icon: FaSearch,
      },
    ],
    process: [
      "Discovery & Goal Mapping",
      "Creative Design & Wireframing",
      "High-Quality Development",
      "Testing & Optimization",
      "Launch & Post-Launch Care",
    ],
    technologies: [
      { name: "HTML5", icon: FaHtml5 },
      { name: "CSS3", icon: FaCss3Alt },
      { name: "JavaScript", icon: FaJs },
      { name: "React", icon: FaReact },
      { name: "Angular", icon: FaAngular },
      { name: "PHP", icon: FaPhp },
      { name: "Node.js", icon: FaNodeJs },
      { name: "Laravel", icon: FaLaravel },
      { name: "Python/Django", icon: FaPython },
    ],
    benefits: [
      "24/7 sales engine",
      "Stronger brand credibility",
      "Increased leads & conversions",
    ],
    whyChooseUs: [
      "Designs that wow and convert",
      "Technology stack ready for future growth",
      "SEO-first approach for higher visibility",
      "Reliable, long-term support",
    ],
  },
  {
    id: 2,
    title: "Mobile App Development",
    slug: "mobile-app-development",
    tagline: "From Concept to Clicks — We Build Apps People Love",
    description:
      "User-friendly mobile apps that keep your business in your customer's pocket.",
    detailedDescription:
      "In a mobile-first world, your business needs to be right in your customer's pocket. We create intuitive, high-performance mobile apps that engage users, build loyalty, and drive growth — whether native, cross-platform, or progressive web apps.",
    icon: FaMobile,
    image:
      "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&q=80",
    category: "Development",
    locations: serviceLocations,
    offerings: [
      {
        title: "Native Android & iOS Development",
        description: "Platform-specific apps for optimal performance.",
        icon: FaMobile,
      },
      {
        title: "Cross-platform Apps",
        description: "Using Flutter & React Native for multiple platforms.",
        icon: FaCode,
      },
      {
        title: "Progressive Web Apps (PWAs)",
        description: "Web apps that work like native mobile apps.",
        icon: FaLaptopCode,
      },
      {
        title: "API Development & Integration",
        description:
          "Seamless backend connectivity and third-party integrations.",
        icon: FaDatabase,
      },
      {
        title: "App Store Optimization",
        description: "Maximize visibility and downloads on app stores.",
        icon: FaChartLine,
      },
      {
        title: "Ongoing Maintenance & Updates",
        description: "Keep your app running smoothly with regular updates.",
        icon: FaTools,
      },
    ],
    process: [
      "Idea Validation & Strategy",
      "UI/UX Design for Engagement",
      "Development & Integration",
      "Quality Assurance & Beta Testing",
      "Launch & Support",
    ],
    technologies: [
      { name: "Swift", icon: FaMobile },
      { name: "Kotlin", icon: FaCode },
      { name: "Flutter", icon: FaMobile },
      { name: "React Native", icon: FaReact },
      { name: "Node.js", icon: FaNodeJs },
      { name: "Firebase", icon: FaDatabase },
      { name: "AWS", icon: FaAws },
    ],
    benefits: [
      "Wider reach",
      "Stronger customer relationships",
      "New revenue streams",
    ],
    whyChooseUs: [
      "Seamless performance across devices",
      "User-first approach for better retention",
      "Scalable solutions for future growth",
    ],
  },
  {
    id: 3,
    title: "Graphic Designing",
    slug: "graphic-designing",
    tagline: "Designs That Speak — Brands That Last",
    description:
      "Eye-catching designs that speak your brand's language and inspire action.",
    detailedDescription:
      "Your visuals define your brand identity. We craft eye-catching, high-impact designs that communicate your message, connect with your audience, and leave a lasting impression.",
    icon: FaPaintBrush,
    image:
      "https://images.unsplash.com/photo-1503602642458-232111445657?w=800&q=80",
    category: "Design",
    locations: serviceLocations,
    offerings: [
      {
        title: "Logo & Brand Identity Design",
        description: "Create memorable brand identities that stand out.",
        icon: FaPaintBrush,
      },
      {
        title: "Social Media Creatives & Banners",
        description: "Engaging visuals for social media platforms.",
        icon: FaShareAlt,
      },
      {
        title: "Marketing Collateral",
        description: "Brochures, flyers, posters for effective marketing.",
        icon: FaBullhorn,
      },
      {
        title: "Packaging Design",
        description: "Product packaging that attracts customers.",
        icon: FaPaintBrush,
      },
      {
        title: "Website & App UI/UX Design",
        description: "User-friendly interfaces that convert.",
        icon: FaDesktop,
      },
      {
        title: "Infographics & Presentations",
        description: "Visual storytelling that engages audiences.",
        icon: FaChartLine,
      },
    ],
    process: [
      "Understanding your brand story",
      "Concept creation & brainstorming",
      "Design execution",
      "Feedback & revisions",
      "Final delivery in multiple formats",
    ],
    technologies: [
      { name: "Adobe Photoshop", icon: FaPaintBrush },
      { name: "Adobe Illustrator", icon: FaPaintBrush },
      { name: "Figma", icon: FaDesktop },
      { name: "CorelDRAW", icon: FaPaintBrush },
      { name: "Canva", icon: FaPaintBrush },
    ],
    benefits: [
      "Stronger visual identity",
      "Better marketing performance",
      "Increased brand recall",
    ],
    whyChooseUs: [
      "Unique, creative concepts",
      "Consistency across all platforms",
      "Designs that convert viewers into customers",
    ],
  },
  {
    id: 4,
    title: "Digital Marketing",
    slug: "digital-marketing-agency",
    tagline: "Turning Clicks into Customers",
    description:
      "Data-driven campaigns that turn clicks into paying customers.",
    detailedDescription:
      "We create data-driven marketing campaigns that connect you with your target audience, boost brand visibility, and increase sales. Our strategies are designed to maximize ROI through the perfect mix of creativity and analytics.",
    icon: FaBullhorn,
    image:
      "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&q=80",
    category: "Marketing",
    locations: serviceLocations,
    offerings: [
      {
        title: "Search Engine Optimization (SEO)",
        description: "Improve your website's visibility on search engines.",
        icon: FaSearch,
      },
      {
        title: "Social Media Marketing & Management",
        description: "Build and engage your social media community.",
        icon: FaShareAlt,
      },
      {
        title: "Google Ads & PPC Campaigns",
        description: "Targeted advertising for immediate results.",
        icon: FaGoogle,
      },
      {
        title: "Content Marketing",
        description: "Create valuable content that attracts customers.",
        icon: FaLaptopCode,
      },
      {
        title: "Email Marketing",
        description: "Direct communication with your audience.",
        icon: FaEnvelope,
      },
      {
        title: "Influencer Partnerships",
        description: "Collaborate with influencers to expand reach.",
        icon: FaUsers,
      },
    ],
    process: [
      "Market & competitor analysis",
      "Strategy development",
      "Campaign execution",
      "Performance tracking & optimization",
    ],
    technologies: [
      { name: "Google Analytics", icon: FaGoogle },
      { name: "SEMrush", icon: FaSearch },
      { name: "Ahrefs", icon: FaChartLine },
      { name: "Meta Ads Manager", icon: FaShareAlt },
      { name: "Mailchimp", icon: FaEnvelope },
    ],
    benefits: [
      "More qualified leads",
      "Stronger brand presence",
      "Increased conversions",
    ],
    whyChooseUs: [
      "ROI-focused campaigns",
      "Transparent reporting",
      "Expertise across multiple channels",
    ],
  },
  {
    id: 5,
    title: "Business Consultation",
    slug: "business-consultation",
    tagline: "Your Success, Strategized",
    description:
      "Smart strategies to solve challenges, scale faster, and grow stronger.",
    detailedDescription:
      "We help businesses identify challenges, discover opportunities, and implement strategies that drive sustainable growth. From startups to enterprises, we guide you in making informed decisions that deliver measurable results.",
    icon: FaHandshake,
    image:
      "https://plus.unsplash.com/premium_photo-1682141025267-9e0ade0c0826?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Z2FtZSUyMGRldmVsb3BtZW50fGVufDB8fDB8fHww",
    category: "Consulting",
    locations: serviceLocations,
    offerings: [
      {
        title: "Business Strategy & Planning",
        description: "Comprehensive strategies for business growth.",
        icon: FaChartLine,
      },
      {
        title: "Process Optimization",
        description: "Streamline operations for better efficiency.",
        icon: FaCog,
      },
      {
        title: "Market Research & Competitor Analysis",
        description: "Understand your market and competition.",
        icon: FaSearch,
      },
      {
        title: "Growth & Scaling Strategies",
        description: "Plans to scale your business effectively.",
        icon: FaChartLine,
      },
      {
        title: "Financial & Operational Advice",
        description: "Expert guidance on financial and operational matters.",
        icon: FaCalculator,
      },
    ],
    process: [
      "Consultation & assessment",
      "Problem identification",
      "Strategic planning",
      "Implementation & monitoring",
    ],
    benefits: [
      "Better decision-making",
      "Increased efficiency",
      "Higher profitability",
    ],
    whyChooseUs: [
      "Industry-specific expertise",
      "Practical, results-driven advice",
      "Confidential & trustworthy partnerships",
    ],
  },
  {
    id: 6,
    title: "Cloud & Hosting Services",
    slug: "cloud-hosting-services",
    tagline: "Secure. Reliable. Scalable.",
    description:
      "Secure, reliable, and scalable hosting to keep your business online 24/7.",
    detailedDescription:
      "We provide secure and high-performance hosting solutions that ensure your website and applications are always online and running smoothly.",
    icon: FaCloud,
    image:
      "https://images.unsplash.com/photo-1603791440384-56cd371ee9a7?w=800&q=80",
    category: "Infrastructure",
    locations: serviceLocations,
    offerings: [
      {
        title: "Shared & Dedicated Hosting",
        description: "Flexible hosting solutions for every need.",
        icon: FaServer,
      },
      {
        title: "Cloud Infrastructure",
        description: "AWS, Azure, Google Cloud solutions.",
        icon: FaCloud,
      },
      {
        title: "Domain Registration & Management",
        description: "Complete domain services and management.",
        icon: FaLaptopCode,
      },
      {
        title: "Website Migration & Backups",
        description: "Safe migration and regular backup services.",
        icon: FaShieldAlt,
      },
      {
        title: "Server Monitoring & Maintenance",
        description: "24/7 monitoring and proactive maintenance.",
        icon: FaTools,
      },
      {
        title: "Disaster Recovery Solutions",
        description: "Comprehensive backup and recovery plans.",
        icon: FaShieldAlt,
      },
    ],
    process: [
      "Needs assessment",
      "Hosting setup & configuration",
      "Security hardening",
      "Ongoing monitoring & support",
    ],
    technologies: [
      { name: "AWS", icon: FaAws },
      { name: "Google Cloud", icon: FaGoogleCloud },
      { name: "Azure", icon: FaCloud },
    ],
    benefits: [
      "Faster load times",
      "Higher security",
      "Hassle-free management",
    ],
    whyChooseUs: [
      "99.9% uptime guarantee",
      "Scalable infrastructure",
      "Strong security protocols",
    ],
  },
  {
    id: 7,
    title: "Accounting & Financial Services",
    slug: "accounting-financial-services",
    tagline: "Simplifying Finances, Maximizing Growth",
    description:
      "Stress-free accounting and compliance so you can focus on growth.",
    detailedDescription:
      "We handle your accounting, compliance, and financial planning so you can focus on growing your business without stress.",
    icon: FaCalculator,
    image:
      "https://plus.unsplash.com/premium_photo-1682141025267-9e0ade0c0826?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Z2FtZSUyMGRldmVsb3BtZW50fGVufDB8fDB8fHww",
    category: "Finance",
    locations: serviceLocations,
    offerings: [
      {
        title: "Bookkeeping & Accounting",
        description: "Complete financial record management.",
        icon: FaFileInvoiceDollar,
      },
      {
        title: "GST, TDS & Income Tax Filing",
        description: "Complete tax compliance services.",
        icon: FaClipboardList,
      },
      {
        title: "Payroll Management",
        description: "Efficient employee payroll processing.",
        icon: FaUsers,
      },
      {
        title: "Financial Statements & Audits",
        description: "Professional financial reporting and audits.",
        icon: FaChartLine,
      },
      {
        title: "ROC & Compliance Filing",
        description: "Regulatory compliance and filing services.",
        icon: FaClipboardList,
      },
      {
        title: "Budgeting & Forecasting",
        description: "Financial planning and forecasting services.",
        icon: FaChartLine,
      },
    ],
    process: [
      "Data collection & verification",
      "Record maintenance",
      "Compliance filing",
      "Reporting & advisory",
    ],
    benefits: [
      "Clear financial picture",
      "Avoid penalties",
      "Strategic growth planning",
    ],
    whyChooseUs: [
      "Accurate & confidential handling",
      "On-time compliance",
      "Expert financial advice",
    ],
  },
  {
    id: 8,
    title: "Lead Generation",
    slug: "lead-generation-services",
    tagline: "More Leads. More Sales. More Growth.",
    description:
      "Targeted leads that boost sales, cut costs, and speed up your sales cycle.",
    detailedDescription:
      "We deliver high-quality, targeted leads that are more likely to convert into paying customers, reducing acquisition costs and boosting sales.",
    icon: FaUsers,
    image:
      "https://www.vanguard86.com/hs-fs/hubfs/Blog%20cover%20images/Smiling%20young%20man%20shaking%20hands%20with%20an%20insurance%20agent%20or%20investment%20adviser%20as%20he%20sits%20in%20a%20meeting%20with%20his%20wife%20in%20her%20office.jpeg?width=1000&name=Smiling%20young%20man%20shaking%20hands%20with%20an%20insurance%20agent%20or%20investment%20adviser%20as%20he%20sits%20in%20a%20meeting%20with%20his%20wife%20in%20her%20office.jpeg",
    category: "Marketing",
    locations: serviceLocations,
    offerings: [
      {
        title: "SEO & Content Marketing",
        description: "Organic lead generation through content.",
        icon: FaSearch,
      },
      {
        title: "Paid Advertising",
        description: "Google, Facebook, Instagram advertising campaigns.",
        icon: FaGoogle,
      },
      {
        title: "Social Media Campaigns",
        description: "Social media lead generation campaigns.",
        icon: FaShareAlt,
      },
      {
        title: "Email Outreach",
        description: "Targeted email marketing campaigns.",
        icon: FaEnvelope,
      },
      {
        title: "Landing Page Optimization",
        description: "High-converting landing pages.",
        icon: FaLaptopCode,
      },
      {
        title: "CRM Integration",
        description: "Seamless lead management systems.",
        icon: FaDatabase,
      },
    ],
    process: [
      "Audience research",
      "Campaign creation",
      "Lead capture & nurturing",
      "Performance analysis",
    ],
    benefits: [
      "Reduced marketing costs",
      "Higher conversion rates",
      "Faster sales cycle",
    ],
    whyChooseUs: [
      "Focus on lead quality over quantity",
      "Cost-effective acquisition strategies",
      "Measurable results",
    ],
  },
  {
    id: 9,
    title: "Software Development",
    slug: "software-development-company",
    tagline: "Custom Solutions for Complex Problems",
    description:
      "Custom software solutions built to streamline your business operations.",
    detailedDescription:
      "We build secure, scalable, and high-performing software tailored to your specific business needs — from automation tools to enterprise-level systems.",
    icon: FaLaptopCode,
    image:
      "https://plus.unsplash.com/premium_photo-1678565869434-c81195861939?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8d2ViJTIwZGV2ZWxvcGVyfGVufDB8fDB8fHww",
    category: "Development",
    locations: serviceLocations,
    offerings: [
      {
        title: "Custom Desktop & Web Applications",
        description: "Tailored software solutions for your business.",
        icon: FaDesktop,
      },
      {
        title: "ERP & CRM Development",
        description: "Enterprise resource planning and customer management.",
        icon: FaDatabase,
      },
      {
        title: "API Development & Integration",
        description: "Connect your systems with powerful APIs.",
        icon: FaCode,
      },
      {
        title: "SaaS Product Development",
        description: "Software as a Service solutions.",
        icon: FaCloud,
      },
      {
        title: "Automation Tools",
        description: "Streamline processes with automation.",
        icon: FaCog,
      },
      {
        title: "Software Maintenance & Upgrades",
        description: "Keep your software up-to-date and secure.",
        icon: FaTools,
      },
    ],
    process: [
      "Requirement gathering",
      "System architecture & design",
      "Development & testing",
      "Deployment & support",
    ],
    technologies: [
      { name: "Python", icon: FaPython },
      { name: "Java", icon: FaCode },
      { name: ".NET", icon: FaCode },
      { name: "Node.js", icon: FaNodeJs },
      { name: "Laravel", icon: FaLaravel },
      { name: "React", icon: FaReact },
      { name: "Angular", icon: FaAngular },
    ],
    benefits: [
      "Increased productivity",
      "Cost savings",
      "Better customer experience",
    ],
    whyChooseUs: [
      "Future-ready technology stack",
      "User-friendly design",
      "Strong focus on performance & security",
    ],
  },
  {
    id: 10,
    title: "SEO Services",
    slug: "seo-services-company",
    tagline: "Rank Higher, Get Found, Grow Faster",
    description:
      "Data-driven SEO strategies that bring your website to the top of search results and drive consistent organic traffic.",
    detailedDescription:
      "In today’s competitive digital world, just having a website is not enough — you need to be visible. Our SEO services help your business rank higher on search engines, attract quality traffic, and convert visitors into customers. From keyword research to on-page optimization and high-quality backlinks, we create a long-term SEO strategy that delivers measurable growth and sustainable results.",
    icon: FaSearch,
    image: seo,
    category: "Marketing",
    locations: serviceLocations,
    offerings: [
      {
        title: "Keyword Research & Strategy",
        description:
          "Finding high-impact keywords your customers are searching for.",
        icon: FaSearch,
      },
      {
        title: "On-Page SEO Optimization",
        description:
          "Optimizing content, meta tags, and structure for better rankings.",
        icon: FaFileAlt,
      },
      {
        title: "Technical SEO",
        description:
          "Improving site speed, indexing, crawlability, and mobile performance.",
        icon: FaCogs,
      },
      {
        title: "Link Building",
        description:
          "High-quality backlinks to boost authority and domain strength.",
        icon: FaLink,
      },
      {
        title: "Local SEO",
        description:
          "Rank your business higher in local search and Google Maps.",
        icon: FaMapMarkerAlt,
      },
      {
        title: "SEO Audits & Reporting",
        description:
          "Detailed reports with insights, performance tracking, and growth plans.",
        icon: FaChartLine,
      },
    ],
    process: [
      "Website Audit & Competitor Analysis",
      "Keyword Research & Planning",
      "On-Page & Technical Optimization",
      "Content Creation & Link Building",
      "Performance Tracking & Continuous Improvement",
    ],
    technologies: [
      { name: "Google Analytics", icon: FaGoogle },
      { name: "Google Search Console", icon: FaSearch },
      { name: "Ahrefs", icon: FaLink },
      { name: "SEMrush", icon: FaChartLine },
      { name: "Screaming Frog", icon: FaBug },
      { name: "Yoast SEO", icon: FaWordpress },
    ],
    benefits: [
      "Higher search engine rankings",
      "Consistent organic traffic growth",
      "Better brand visibility & trust",
      "Long-term ROI without paid ads",
    ],
    whyChooseUs: [
      "Proven SEO strategies that deliver results",
      "White-hat techniques for long-term success",
      "Transparent reporting and communication",
      "Dedicated experts focused on your growth",
    ],
  },
];

// Helper function to get service by ID
export const getServiceById = (id) => {
  return servicesData.find((service) => service.id === parseInt(id));
};

// Helper function to get services by category
export const getServicesByCategory = (category) => {
  return servicesData.filter((service) => service.category === category);
};

// Helper function to get all categories
export const getAllCategories = () => {
  return [...new Set(servicesData.map((service) => service.category))];
};

// Location-wise service details.
export const locationServiceData = {
  generateLocationData: (service, location) => {
    return {
      service: service.title,
      location: location,
      title: `${service.title} in ${location}`,
      metaDescription: `Looking for professional ${service.title.toLowerCase()} in ${location}? We offer top-quality ${service.title.toLowerCase()} services in ${location} with experienced team and affordable pricing.`,
      heroTitle: `Best ${service.title} Services in ${location}`,
      heroDescription: `Transform your business with our expert ${service.title.toLowerCase()} services in ${location}. Trusted by local businesses for quality and reliability.`,
      whyChooseLocal: [
        `Local team based in ${location}`,
        `Quick response time for ${location} clients`,
        `Understanding of ${location} market dynamics`,
        `On-site support available in ${location}`,
        `Proven track record in ${location} area`,
      ],
      localStats: [
        { label: "Projects Completed", value: "50+", suffix: "" },
        { label: "Happy Clients", value: "100+", suffix: "" },
        { label: "Years Experience", value: "5+", suffix: "" },
        { label: "Response Time", value: "24", suffix: "hrs" },
      ],
      nearbyAreas: service.locations
        .filter((loc) => loc !== location)
        .slice(0, 8),
      testimonial: {
        text: `Excellent ${service.title.toLowerCase()} service! The team was professional, delivered on time, and exceeded our expectations. Highly recommend for anyone in ${location}.`,
        author: "Local Business Owner",
        location: location,
        rating: 5,
      },
    };
  },
};
